# Generated by Django 4.2.10 on 2024-03-08 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Автор", "verbose_name_plural": "Авторы"},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(default=5, verbose_name="Рейтинг отзыва"),
                ),
                ("review", models.TextField(verbose_name="Отзыв")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Отзывы",
                    ),
                ),
            ],
        ),
    ]
